name = "jamonianlord-blue-chance-connect"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = ".output/server"

[vars]
NODE_VERSION = "20"